/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

 import com.github.spotbugs.snom.SpotBugsTask

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.spotbugs)
    alias(libs.plugins.spotless)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    // JackBot doesn't need this dependency but for now keep it as a comment as a placeholder
    // implementation(libs.guava)

    compileOnly("com.github.spotbugs:spotbugs-annotations:4.8.3")
    testCompileOnly("com.github.spotbugs:spotbugs-annotations:4.8.3")
}

spotbugs {
    toolVersion.set("4.8.3") // SpotBugs engine version
    effort.set(com.github.spotbugs.snom.Effort.DEFAULT)
    reportLevel.set(com.github.spotbugs.snom.Confidence.LOW)
}

spotless {
  java {
    // Use the default importOrder configuration
    importOrder()

    removeUnusedImports()
    forbidWildcardImports()

    // Cleanthat will refactor your code, but it may break your style: apply it before your formatter
    // For now comment it out
    // cleanthat()

    // Formatter
    googleJavaFormat()

    formatAnnotations()  // fixes formatting of type annotations, see below
  }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.jackbot.JackBot"
}

tasks.withType<SpotBugsTask>().configureEach {
    // fail the build if SpotBugs finds issues
    ignoreFailures = false

    reports.create("html") {
        required = true
        outputLocation = file("$buildDir/reports/spotbugs/${name}.html")
    }
    // optional: also generate XML (handy for CI tooling)
    reports.create("xml") {
        required = false
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
